export const locationSeeds = [
  {
    Name: "RSU Duren Sawit",
    Address: "Jl. Raden Inten II No.1",
    City: "Jakarta",
    Phone: "021-86613200",
  },
  {
    Name: "RSU Matcha",
    Address: "Jl. Kesehatan No.1",
    City: "Surabaya",
    Phone: "031-5501078",
  },
  {
    Name: "RSU Kebon Jeruk",
    Address: "Jl. Kebon Jeruk Raya No.1",
    City: "Madiun",
    Phone: "021-53650111",
  },
  {
    Name: "RSU Jambu Merah",
    Address: "Jl. Jambu Merah No.1",
    City: "Bandung",
    Phone: "022-2033003",
  },
  {
    Name: "RSU Melon Kuning",
    Address: "Jl. Melon Kuning No.1",
    City: "Semarang",
    Phone: "024-8310000",
  },
  // {
  //   Name: "RSU Apel Hijau",
  //   Address: "Jl. Apel Hijau No.2",
  //   City: "Jakarta",
  //   Phone: "021-8674001",
  // },
  // {
  //   Name: "RSU Nanas Manis",
  //   Address: "Jl. Nanas Manis No.3",
  //   City: "Bogor",
  //   Phone: "0251-8391001",
  // },
  // {
  //   Name: "RSU Mangga Rasa",
  //   Address: "Jl. Mangga Rasa No.4",
  //   City: "Depok",
  //   Phone: "021-8749992",
  // },
  // {
  //   Name: "RSU Anggur Putih",
  //   Address: "Jl. Anggur Putih No.5",
  //   City: "Bekasi",
  //   Phone: "021-8881002",
  // },
  // {
  //   Name: "RSU Pisang Raja",
  //   Address: "Jl. Pisang Raja No.6",
  //   City: "Tangerang",
  //   Phone: "021-7321113",
  // },
  // {
  //   Name: "RSU Jeruk Bali",
  //   Address: "Jl. Jeruk Bali No.7",
  //   City: "Medan",
  //   Phone: "061-4532003",
  // },
  // {
  //   Name: "RSU Melati Indah",
  //   Address: "Jl. Melati Indah No.8",
  //   City: "Palembang",
  //   Phone: "0711-372004",
  // },
  // {
  //   Name: "RSU Teratai Putih",
  //   Address: "Jl. Teratai Putih No.9",
  //   City: "Banda Aceh",
  //   Phone: "0651-311005",
  // },
  // {
  //   Name: "RSU Mawar Merah",
  //   Address: "Jl. Mawar Merah No.10",
  //   City: "Padang",
  //   Phone: "0751-842006",
  // },
  // {
  //   Name: "RSU Kamboja Hitam",
  //   Address: "Jl. Kamboja Hitam No.11",
  //   City: "Makassar",
  //   Phone: "0411-856007",
  // },
  // {
  //   Name: "RSU Melur Wangi",
  //   Address: "Jl. Melur Wangi No.12",
  //   City: "Manado",
  //   Phone: "0431-838008",
  // },
  // {
  //   Name: "RSU Tulip Cantik",
  //   Address: "Jl. Tulip Cantik No.13",
  //   City: "Yogyakarta",
  //   Phone: "0274-844009",
  // },
  // {
  //   Name: "RSU Kenanga Biru",
  //   Address: "Jl. Kenanga Biru No.14",
  //   City: "Denpasar",
  //   Phone: "0361-722010",
  // },
  // {
  //   Name: "RSU Cempaka Kuning",
  //   Address: "Jl. Cempaka Kuning No.15",
  //   City: "Pontianak",
  //   Phone: "0561-372011",
  // },
  // {
  //   Name: "RSU Dahlia Ungu",
  //   Address: "Jl. Dahlia Ungu No.16",
  //   City: "Banjarmasin",
  //   Phone: "0511-376012",
  // },
];
