export const psikologSeeds = [
  {
    Name: "Dr. John Doe",
    Email: "john.doe@example.com",
    Specialty: "Child Psychology",
    Mobile: "081234567890",
    VisitPrice: 500000.0,
    Location_LocationID: 1,
  },
  {
    Name: "Dr. Jane Smith",
    Email: "jane.smith@example.com",
    Specialty: "Clinical Psychology",
    Mobile: "082345678901",
    VisitPrice: 600000.0,
    Location_LocationID: 1,
  },
  {
    Name: "Dr. Bob Johnson",
    Email: "bob.johnson@example.com",
    Specialty: "Counseling Psychology",
    Mobile: "083456789012",
    VisitPrice: 450000.0,
    Location_LocationID: 2,
  },
  {
    Name: "Dr. Samantha Lee",
    Email: "samantha.lee@example.com",
    Specialty: "Forensic Psychology",
    Mobile: "084567890123",
    VisitPrice: 700000.0,
    Location_LocationID: 2,
  },
  {
    Name: "Dr. Michael Brown",
    Email: "michael.brown@example.com",
    Specialty: "Health Psychology",
    Mobile: "085678901234",
    VisitPrice: 550000.0,
    Location_LocationID: 3,
  },
  {
    Name: "Dr. Emily Davis",
    Email: "emily.davis@example.com",
    Specialty: "Industrial-Organizational Psychology",
    Mobile: "086789012345",
    VisitPrice: 650000.0,
    Location_LocationID: 3,
  },
  {
    Name: "Dr. David Wilson",
    Email: "david.wilson@example.com",
    Specialty: "Neuropsychology",
    Mobile: "087890123456",
    VisitPrice: 800000.0,
    Location_LocationID: 4,
  },
  {
    Name: "Dr. Sophia Martinez",
    Email: "sophia.martinez@example.com",
    Specialty: "School Psychology",
    Mobile: "088901234567",
    VisitPrice: 500000.0,
    Location_LocationID: 4,
  },
  {
    Name: "Dr. Christopher Garcia",
    Email: "christopher.garcia@example.com",
    Specialty: "Sports Psychology",
    Mobile: "089012345678",
    VisitPrice: 600000.0,
    Location_LocationID: 5,
  },
  {
    Name: "Dr. Olivia Rodriguez",
    Email: "olivia.rodriguez@example.com",
    Specialty: "Trauma Psychology",
    Mobile: "081123456789",
    VisitPrice: 650000.0,
    Location_LocationID: 5,
  },
  {
    Name: "Dr. Daniel Johnson",
    Email: "daniel.johnson@example.com",
    Specialty: "Child Psychology",
    Mobile: "082234567890",
    VisitPrice: 550000.0,
    Location_LocationID: 6,
  },
  {
    Name: "Dr. Ava Williams",
    Email: "ava.williams@example.com",
    Specialty: "Clinical Psychology",
    Mobile: "083345678901",
    VisitPrice: 700000.0,
    Location_LocationID: 6,
  },
  {
    Name: "Dr. Matthew Jones",
    Email: "matthew.jones@example.com",
    Specialty: "Counseling Psychology",
    Mobile: "084456789012",
    VisitPrice: 600000.0,
    Location_LocationID: 7,
  },
  {
    Name: "Dr. Isabella Brown",
    Email: "isabella.brown@example.com",
    Specialty: "Forensic Psychology",
    Mobile: "085567890123",
    VisitPrice: 750000.0,
    Location_LocationID: 7,
  },
  {
    Name: "Dr. Andrew Miller",
    Email: "andrew.miller@example.com",
    Specialty: "Health Psychology",
    Mobile: "086678901234",
    VisitPrice: 650000.0,
    Location_LocationID: 8,
  },
  {
    Name: "Dr. Emma Davis",
    Email: "emma.davis@example.com",
    Specialty: "Industrial-Organizational Psychology",
    Mobile: "087789012345",
    VisitPrice: 700000.0,
    Location_LocationID: 8,
  },
  {
    Name: "Dr. Joshua Wilson",
    Email: "joshua.wilson@example.com",
    Specialty: "Neuropsychology",
    Mobile: "088890123456",
    VisitPrice: 850000.0,
    Location_LocationID: 1,
  },
  {
    Name: "Dr. Abigail Rodriguez",
    Email: "abigail.rodriguez@example.com",
    Specialty: "School Psychology",
    Mobile: "089901234567",
    VisitPrice: 600000.0,
    Location_LocationID: 2,
  },
  {
    Name: "Dr. Joseph Thompson",
    Email: "joseph.thompson@example.com",
    Specialty: "Sports Psychology",
    Mobile: "081012345678",
    VisitPrice: 650000.0,
    Location_LocationID: 3,
  },
  {
    Name: "Dr. Mia Garcia",
    Email: "mia.garcia@example.com",
    Specialty: "Trauma Psychology",
    Mobile: "082123456789",
    VisitPrice: 700000.0,
    Location_LocationID: 4,
  },
  {
    Name: "Dr. William Martinez",
    Email: "william.martinez@example.com",
    Specialty: "Child Psychology",
    Mobile: "083234567890",
    VisitPrice: 550000.0,
    Location_LocationID: 5,
  },
  {
    Name: "Dr. Sophia Anderson",
    Email: "sophia.anderson@example.com",
    Specialty: "Clinical Psychology",
    Mobile: "084345678901",
    VisitPrice: 750000.0,
    Location_LocationID: 6,
  },
  {
    Name: "Dr. Michael Taylor",
    Email: "michael.taylor@example.com",
    Specialty: "Counseling Psychology",
    Mobile: "085456789012",
    VisitPrice: 650000.0,
    Location_LocationID: 7,
  },
  {
    Name: "Dr. Olivia Thomas",
    Email: "olivia.thomas@example.com",
    Specialty: "Forensic Psychology",
    Mobile: "086567890123",
    VisitPrice: 800000.0,
    Location_LocationID: 8,
  },
  {
    Name: "Dr. David Jackson",
    Email: "david.jackson@example.com",
    Specialty: "Health Psychology",
    Mobile: "087678901234",
    VisitPrice: 700000.0,
    Location_LocationID: 1,
  },
  {
    Name: "Dr. Ava Harris",
    Email: "ava.harris@example.com",
    Specialty: "Industrial-Organizational Psychology",
    Mobile: "088789012345",
    VisitPrice: 750000.0,
    Location_LocationID: 2,
  },
  {
    Name: "Dr. Joseph Clark",
    Email: "joseph.clark@example.com",
    Specialty: "Neuropsychology",
    Mobile: "089890123456",
    VisitPrice: 900000.0,
    Location_LocationID: 3,
  },
  {
    Name: "Dr. Mia Lewis",
    Email: "mia.lewis@example.com",
    Specialty: "School Psychology",
    Mobile: "081901234567",
    VisitPrice: 650000.0,
    Location_LocationID: 4,
  },
  {
    Name: "Dr. William Robinson",
    Email: "william.robinson@example.com",
    Specialty: "Sports Psychology",
    Mobile: "082012345678",
    VisitPrice: 700000.0,
    Location_LocationID: 5,
  },
  {
    Name: "Dr. Sophia Walker",
    Email: "sophia.walker@example.com",
    Specialty: "Trauma Psychology",
    Mobile: "083123456789",
    VisitPrice: 750000.0,
    Location_LocationID: 6,
  },
];
